---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment
  - name: compiled-bosh-release

outputs:
  - name: bosh-deployment-output

run:
  path: bosh-deployment/ci/tasks/use-latest-bosh.sh
