- type: replace
  path: /resource_pools/name=vms/cloud_properties/mounts?/-
  value:
    type: bind
    source: ((docker_host))
    target: /docker/docker.sock # Place into location that's not bosh or systemd managed

- type: replace
  path: /instance_groups/name=bosh/properties/docker_cpi/docker/host
  value: unix:///docker/docker.sock

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_additional_volumes?
  value:
  - path: /docker/docker.sock
    writable: true

- type: remove
  path: /instance_groups/name=bosh/properties/docker_cpi/docker/tls

- type: remove
  path: /cloud_provider/properties/docker_cpi/docker/tls
