- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: 598c2b1ce0dcb31dacfe7f54e54ab7c4f926adce
    url: https://storage.googleapis.com/bosh-core-stemcells/1.1282/bosh-stemcell-1.1282-warden-boshlite-ubuntu-jammy-go_agent.tgz
