- path: /releases/name=bosh-docker-cpi?
  release: bosh-docker-cpi
  type: replace
  value:
    name: bosh-docker-cpi
    sha1: 913fe1806199f981ca4e3b81117cbfca214f1d44
    url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-docker-cpi-0.2.19-ubuntu-resolute-0.93.tgz
    version: 0.2.19
- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: 1af174f4ff1a5fd11923ab3626c8c78ebb5220e5
    url: https://storage.googleapis.com/bosh-core-stemcells/0.93/bosh-stemcell-0.93-warden-boshlite-ubuntu-resolute.tgz
