- path: /releases/name=bosh-docker-cpi?
  release: bosh-docker-cpi
  type: replace
  value:
    name: bosh-docker-cpi
    sha1: e96d8794e48880b2577201a93c2b8a3be11c245d
    url: https://bosh-compiled-release-tarballs.s3.amazonaws.com/bosh-docker-cpi-0.2.21-ubuntu-resolute-0.146.tgz
    version: 0.2.21
- name: stemcell
  path: /resource_pools/name=vms/stemcell?
  type: replace
  value:
    sha1: 6f4c310a1d211de56dbfdb2542d53460b4db2a1a
    url: https://storage.googleapis.com/bosh-core-stemcells/0.146/bosh-stemcell-0.146-warden-boshlite-ubuntu-resolute.tgz
