azs:
- name: z1
  cloud_properties:
    datacenter: { name: ((sl_datacenter)) }
- name: z2
  cloud_properties:
    datacenter: { name: ((sl_datacenter)) }
- name: z3
  cloud_properties:
    datacenter: { name: ((sl_datacenter)) }

vm_types:
- name: default
  cloud_properties:
    instance_type: 1
    availability_zone: lon02

disk_types:
- name: default
  disk_size: 100_000
- name: small
  disk_size: 20_000
- name: large
  disk_size: 250_000

networks:
- name: default
  type: manual
  cloud_properties:
    net_id: ((network_id))

- name: dynamic
  type: dynamic
  dns: [((internal_ip)), 8.8.8.8, 10.0.80.11, 10.0.80.12]
  cloud_properties:
    net_id: ((network_id))

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: default
  network: dynamic
