azs:
- name: z1
  cloud_properties:
    availability_zone: ((az1))
- name: z2
  cloud_properties:
    availability_zone: ((az2))
- name: z3
  cloud_properties:
    availability_zone: ((az3))

vm_types:
- name: default
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk: {size: 25_000}
- name: large
  cloud_properties:
    instance_type: m4.xlarge
    ephemeral_disk: {size: 50_000}

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr1))
    gateway: ((internal_gw1))
    azs: [z1]
    dns: [8.8.8.8]
    reserved: [((internal_gw1))/30]
    cloud_properties:
      subnet: ((subnet_id1))
  - range: ((internal_cidr2))
    gateway: ((internal_gw2))
    azs: [z2]
    dns: [8.8.8.8]
    reserved: [((internal_gw2))/30]
    cloud_properties:
      subnet: ((subnet_id2))
  - range: ((internal_cidr3))
    gateway: ((internal_gw3))
    azs: [z3]
    dns: [8.8.8.8]
    reserved: [((internal_gw3))/30]
    cloud_properties:
      subnet: ((subnet_id3))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
