
- type: replace
  path: /instance_groups/name=bosh/properties/director/default_ssh_options?/gateway_host
  value: ((loadbalancer_ip))

# todo should not access non-defined vars
- type: replace
  path: /cloud_provider/mbus
  value: https://mbus:((mbus_bootstrap_password))@((loadbalancer_ip)):6868

- type: replace
  path: /resource_pools/name=vms/cloud_properties?/services?/-
  value:
    name: bosh-external

- type: replace
  path: /variables/name=mbus_bootstrap_ssl/options/alternative_names/-
  value: ((loadbalancer_ip))

- type: replace
  path: /variables/name=director_ssl/options/alternative_names/-
  value: ((loadbalancer_ip))
